# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{supermarket}
  s.version = "0.0.2"
  s.platform = %q{universal-java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Berkel"]
  s.date = %q{2010-03-29}
  s.default_executable = %q{market}
  s.description = %q{An unoffical/reverse engineered API for Android market.}
  s.email = %q{jan.berkel@gmail.com}
  s.executables = ["market"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "bin/market",
     "lib/supermarket.rb",
     "lib/supermarket/formats.rb",
     "lib/supermarket/jars/AndroidMarketApi.jar",
     "lib/supermarket/jars/protobuf-format-java-1.2-SNAPSHOT.jar",
     "lib/supermarket/jars/protobuf-java-2.2.0.jar",
     "lib/supermarket/session.rb"
  ]
  s.homepage = %q{http://github.com/jberkel/supermarket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{JRuby bindings for android-market-api}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json-jruby>, [">= 0"])
    else
      s.add_dependency(%q<json-jruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<json-jruby>, [">= 0"])
  end
end

